# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :sphinxs do |sphinxsconfig|
	sphinxsconfig.vm.box = 'centos6'
	sphinxsconfig.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	sphinxsconfig.vm.hostname = 'sphinxs'
	sphinxsconfig.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "1024", "--cpuexecutioncap", "60"] 
	end
	sphinxsconfig.vm.network :private_network, ip: "192.168.80.10"
	sphinxsconfig.vm.network  :forwarded_port, guest:22, host:2525
	sphinxsconfig.vm.provision :puppet do |sphinxspuppet|
		sphinxspuppet.options = '--verbose'
		sphinxspuppet.module_path= "modules"
	end
   end

end
