# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define :client_i33810 do |client_i33810|
		client_i33810.vm.box = "ubuntu1204"
		client_i33810.vm.box_url = "http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box"
	end

	config.vm.define :server_i33810 do |server_i33810|
		server_i33810.vm.box = "ubuntu1204"
		server_i33810.vm.box_url = "http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box"
	end
end
