# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :mariadb1 do |mariadb_config|
	mariadb_config.vm.box = 'centos6'
        mariadb_config.vm.network :forwarded_port, guest: 22, host: 3434
	mariadb_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	mariadb_config.vm.hostname = 'mariadb1'
	mariadb_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "512", "--cpuexecutioncap", "60"] 
	end
	mariadb_config.vm.network :private_network, ip: "192.168.80.10"
	mariadb_config.vm.provision :puppet do |mariadb_puppet|
	mariadb_puppet.options = '--verbose'
	mariadb_puppet.module_path= "modules"
	end
   end
  config.vm.define :mariadb2 do |mariadb_config|
	mariadb_config.vm.box = 'centos6'
        mariadb_config.vm.network :forwarded_port, guest: 22, host: 3435
	mariadb_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	mariadb_config.vm.hostname = 'mariadb2'
	mariadb_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "512", "--cpuexecutioncap", "60"] 
	end
	mariadb_config.vm.network :private_network, ip: "192.168.80.11"
	mariadb_config.vm.provision :puppet do |mariadb_puppet|
	mariadb_puppet.options = '--verbose'
	mariadb_puppet.module_path= "modules"
	end
   end
  config.vm.define :mariadb2 do |mariadb_config|
	mariadb_config.vm.box = 'centos6'
        mariadb_config.vm.network :forwarded_port, guest: 22, host: 3436
	mariadb_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	mariadb_config.vm.hostname = 'mariadb3'
	mariadb_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "512", "--cpuexecutioncap", "60"] 
	end
	mariadb_config.vm.network :private_network, ip: "192.168.80.12"
	mariadb_config.vm.provision :puppet do |mariadb_puppet|
	mariadb_puppet.options = '--verbose'
	mariadb_puppet.module_path= "modules"
	end
   end

end
