# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :ignite_go do |ignite_go_config|
	ignite_go_config.vm.box = 'centos6'
	ignite_go_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	ignite_go_config.vm.hostname = 'ignitego'
	ignite_go_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "1024" ] 
	end
	ignite_go_config.vm.network :private_network, ip: "192.168.80.44"
	ignite_go_config.vm.provision :puppet do |ignite_go_puppet|
		ignite_go_puppet.options = '--verbose'
		ignite_go_puppet.module_path= "modules"
	end
   end

end
