# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :ps51 do |ps51_config|
	ps51_config.vm.box = 'centos6'
	ps51_config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box' 
	ps51_config.vm.hostname = 'ps51'
	ps51_config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "1024", "--cpuexecutioncap", "60"] 
	end
	ps51_config.vm.network :private_network, ip: "192.168.80.24"
	ps51_config.vm.provision :puppet do |ps51_puppet|
		ps51_puppet.options = '--verbose'
		ps51_puppet.module_path= "modules"
	end
   end

end
